apiVersion: v1
kind: Secret
metadata:
  name: my-docker-secret
data:
  config.json: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbWd0WldVdGNISmlhVzVrWVd3cmRHVnpkRHBXUlVkQlNWcExVVkl4TlRSUFVWUk5PRUpRVjBaUlNFTkRRVTFMTVVZM1RUQk1SMFZMV2xsSlIwbFlTbGMwU0RCTVdqUTVOa1ZZTVRoVVFUSlJVakF6IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=