---
name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Define the version you want to release'
        required: true
        default: '0.0.1'

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: github-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make RELEASE_VERSION=v${{github.event.inputs.version}} github-release